version: '3.7'
services:
  php-apache:
    image: gitlab.itpeople.dev:4567/medicina/medicina-pricelist/php-apache:${BRANCH_NAME}
    build:
      context: .
      dockerfile: ./.docker/php-apache/Dockerfile
    volumes:
      - ${BITRIX_DIR}:/var/www/html/app/src/bitrix
      - ${UPLOAD_DIR}:/var/www/html/app/src/upload
    ports:
      - ${HTTP_PORT}:80
    restart: always