version: '3.7'
services:
  php-apache:
    build:
      args:
        #RUN_BUILD_SCRIPT: 'false'
        APACHE_USER_ID: 1000
        APACHE_GROUP_ID: 1000
    #volumes:
      #- .:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mariadb:10.4-bionic
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_HOST: mysql
    depends_on:
      - mysql